### ISSUE TITLE
How do I disable CERTIFICATE_VERIFY ?

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-api-client-python#35]
Hi,

I am thinking of using this python api client.
Is there a support to disable "CERTIFICATE_VERIFY" since I am using http connection 

```

[me@miq01t manageiq-api-client-python]$ python example.py

Authenticating with the user credentials: admin / smartvm
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    client = MiqApi(url, dict(user=username, password=password))
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 39, in __init__
    self._load_data()
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 58, in _load_data
    data = self.get(self._entry_point)
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 111, in get
    partial(self._session.get, url, params=get_params))
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 106, in _sending_request
    raise last_connection_exception
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
[me@miq01t manageiq-api-client-python]$


```

**Comment by cben** [comment]
To you talk to an HTTP server, just use an `http://` url, e.g. `http://localhost:3000/api`.
But if I try to connect with `https://` url to an http server, I get a different error (`requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))`).

So I suspect what you mean is you have HTTPS connection, but with a self-signed certificate?

- You can disable validation by passing `ManageIQClient(..., verify_ssl=False)`.  This is insecure.
- For a secure connection, put a CA certificate that generated the self-signed cert in a file, and pass its path by `ManageIQClient(..., ca_bundle_path='/path/to/cert')`.

https://github.com/ManageIQ/manageiq-api-client-python/blob/master/src/manageiq_client/api.py#L24

**Comment by tjyang** [comment]
@cben , Thanks for the help. I  am able to query remote miq on https port by disabling the ssl verification.
