### ISSUE TITLE
Docker manageIQ 

### ISSUE THREAD

**Issue by lexxito** [ManageIQ/manageiq-api-client-python#40]
Good day! 

I am trying to use API client together with docker container. For some reason, container starts  SSL-enabled and client can't be connected. 

I am having an error: 
manageiq_client.api.APIException: JSONDecodeError: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
</body></html>

Have you tried your client with manageiq docker? 
Do you know how can it be solved? 

best,
Oleksii

**Comment by cben** [comment]
I'd used the client long ago against a manageiq container and it worked then.
What parameters are you passing to `MiqApi()`?  Did you try an `https://` URL instead of `http://`?

**Comment by lexxito** [comment]
Sorry for late answer, I have just seen it. 

It seems to be working with disabled ssl: 

client = MiqApi('https://127.0.0.1:8443/api', dict(user='admin', password='smartvm'), verify_ssl=False)

although at the same time a warning is displayed: 

path: : InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

**Comment by cben** [comment]
OK, this makes sense, not a bug.  Container is using self-signed certificate, client behaves as expected.

Instead of insecure `verify_ssl=False`, you put CA certificate in a file, and pass its path by `ca_bundle_path='/path/to/cert'`.

- [ ] need to document both options in README.

I'm not sure how manageiq container gets its self-signed certificate — how to get CA cert, or how to provide your own certs.  Let me know if you need help figuring it out.  Are you using the monolithic 'manageiq/manageiq' container, or separate pods from https://github.com/ManageIQ/manageiq-pods?

P.S. Just to be sure, are you connecting to the right server?  I'm slightly surprised at 8443 port number.  That sounds like k8s/openshift API port, not typically used by manageiq API (though you can make it run on any number of course).
- monolithic container by default exposes 443 https (and 22 ssh) https://hub.docker.com/r/manageiq/manageiq/~/dockerfile/
- Not sure about podified.  manageiq-webserver-worker *container* exposes 3000, but I think there is httpd container in front of it, I see http 80 in [template](https://github.com/ManageIQ/manageiq-pods/blob/master/templates/miq-template.yaml) not sure about 443 https (?)

**Comment by lexxito** [comment]
Where can I get the CA certificate? can it be generated? 

Well, I am using a monolithic ManageIQ image.

It also seemed to me weird that MangeIQ is running under 8443 port, 
but  it was a command from getting started guide: http://manageiq.org/docs/get-started/docker

**Comment by cben** [comment]
Ah, cool, port is right then :)

CA is good question, could you ask this on talk.manageiq.org ?  Can't dig
into it now, if you don't get answers please ping me next week and I'll
also try to find out.
